AWSTemplateFormatVersion: '2010-09-09'
Description: DNS/Route53 config for cornetto.cloud
Parameters:
  dnsPrefix:
    Description: DNS Domain prefix, e.g. 'flunkimat'
    Type: String

  distributionName:
    Description: Cloudfront distribution name
    Type: String

  dnsBaseName:
    Description: DNS Domain , f.e. 'cornetto.cloud.'
    ConstraintDescription: "Value must be a dns name and end with a dot"
    AllowedPattern: ".*"
    Type: String


# -----------------------------------------------------------------------------------------
Resources:
# -----------------------------------------------------------------------------------------

  # -----------------------------------------------------------------------------------------
  # DNS Route53
  # -----------------------------------------------------------------------------------------
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub ${dnsBaseName}.
      Comment: Route alias
      Name: !Sub ${dnsPrefix}.${dnsBaseName}.
      Type: A
      AliasTarget:
        DNSName: !Ref distributionName
        HostedZoneId: 'Z2FDTNDATAQYW2' #Zone Id for Cloudfront, see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html

# -----------------------------------------------------------------------------------------
# OUTPUTS
# -----------------------------------------------------------------------------------------
Outputs:
  dnsRecord:
    Value: '|Ref|DnsRecord'
    Description: domain name

