AWSTemplateFormatVersion: '2010-09-09'
Description: Index Page (S3 and Cloudfront) for dutrinkst
Parameters:
  bucketName:
    Description: Assets bucket name
    Type: String
  certificateArn:
    Description: certificate arn
    Type: String
  apiGatewayRestApiId:
    Description: id of the api gateway restapi resource
    Type: String
  domainName:
    Description: domain name for cloudfront
    Type: String


Resources:
   S3Bucket:
     Type: 'AWS::S3::Bucket'
     Properties:
       BucketName: !Ref bucketName
       AccessControl: PublicRead
       WebsiteConfiguration:
         IndexDocument: index.html
         ErrorDocument: error.html
     DeletionPolicy: Retain
   BucketPolicy:
     Type: 'AWS::S3::BucketPolicy'
     Properties:
       PolicyDocument:
         Id: AllowPublicAccessToBucketPolicy
         Version: '2012-10-17'
         Statement:
           - Sid: PublicReadForGetBucketObjects
             Effect: Allow
             Principal: '*'
             Action: 's3:GetObject'
             Resource: !Sub arn:aws:s3:::${S3Bucket}/*
       Bucket: !Ref S3Bucket


   WebpageCDN:
     Type: AWS::CloudFront::Distribution
     DependsOn:
       - S3Bucket
     Properties:
       DistributionConfig:
         Aliases:
           - !Ref domainName
         DefaultCacheBehavior:
           ForwardedValues:
             QueryString: true
           TargetOriginId: webpage
           ViewerProtocolPolicy: redirect-to-https
         CacheBehaviors:
           - AllowedMethods:
               - DELETE
               - GET
               - HEAD
               - OPTIONS
               - PATCH
               - POST
               - PUT
             CachedMethods:
               - GET
               - HEAD
               - OPTIONS
             Compress: true
             ForwardedValues:
               Headers:
                 - Accept
                 - Referer
                 - Athorization
                 - Content-Type
               QueryString: true
             PathPattern: "/api/*"
             TargetOriginId: api
             ViewerProtocolPolicy: https-only
         DefaultRootObject: index.html
         Enabled: true
         Origins:
           - DomainName:
               Fn::GetAtt: [ S3Bucket , "DomainName" ]
             Id: webpage
             S3OriginConfig:
               OriginAccessIdentity:
                 Ref: AWS::NoValue
           - DomainName: !Sub ${apiGatewayRestApiId}.execute-api.${AWS::Region}.amazonaws.com
             Id: api
             CustomOriginConfig:
               OriginProtocolPolicy: https-only
             OriginPath: /pro
         PriceClass: PriceClass_100
         ViewerCertificate:
           AcmCertificateArn: !Ref certificateArn
           SslSupportMethod: sni-only


Outputs:
  WebsiteURL:
    Value: !GetAtt S3Bucket.WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Sub https://${S3Bucket.DomainName}
    Description: Name of S3 bucket to hold website content
  DistributionName:
    Value: !GetAtt WebpageCDN.DomainName
    Description: domain name of cloudfront distribution
